### ISSUE TITLE
Binding for complex props

### ISSUE THREAD

**Issue by rborn** [wix/BindingListView#3]
I tried to insert an image, but the `source={{uri:'https://blah'}}` won't work.
If I put it in the `_render` method all goes fine (so the image is rendered) only that it's not updated when recycled :)

Any ideas?
Thank you

**Comment by talkol** [comment]
it mostly depends on what view it is.. it's not always clear from the JSX what's the correct way to bind

I added support for images here:
https://github.com/wix/BindingListView/commit/398b161029a7213430c74399b896dac31e53d8f5

**Comment by rborn** [comment]
That's amazing, there is a small issue though, the image get recycled and reloaded.

To replicate change [this](https://github.com/wix/BindingListView/blob/master/src/app.js#L35) to `image: [{uri: `https://unsplash.it/100/100?image=${i}`}]`

Here is what I mean 😄 

![img_flicker](https://cloud.githubusercontent.com/assets/406409/24191194/54b25d54-0eeb-11e7-8d6b-fe60693a2274.gif)



BTW, what's the best way for you guys to handle the issues? Not sure the comments on closed issues will get to you 😟

**Comment by talkol** [comment]
Don't worry, I get messages on all issues, even closed ones :)

Regarding the loading time for the image.. here is what's going on: 

The native UITableView is only populating the cells as they appear on screen. Once it sets the image URL, the device goes to download the image from the web.

Since the images you're using always have new URLs they're not previously cached and have to be downloaded. Even if you would have reused the same images from unsplash.it (by using `https://unsplash.it/100/100?image=${i%10}` for example), the HTTP caching headers from unsplash.it actually require the device to make an HTTP request and get 304 unmodified in order to know the images didn't change, which isn't immediate as well (it's a round trip to the server).

All this means that it takes a little while for the device to get the image, and that's why you're seeing the delay. It's actually not related to React Native stuff, you would have the same behavior in pure native.

The way around it is to prefetch the images in some way. You can either try to do this manually (download the images in advance and hope they are cached). Or we can try to make UITableView preload some cells on the bottom. Preloading has a lot of [discussion in native](http://stackoverflow.com/questions/12662450/preload-cells-of-uitableview).. but again, it's not super related to React Native. A pure native implementation would have needed the same optimizations.

**Comment by rborn** [comment]
@talkol 

Ok, makes a lot of sense. I ran some tests and indeed imgur replies very fast (34ms in my case) so I think the rendering was really fast.
But I found that if you add `cache: 'force-cache'` the behaviour is improved a lot.

It will still be visible if you scroll like crazy but it's an improvement.
Thanks :)
